language: python

python:
  - 2.7

sudo: required

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq erlang-dev

install:
  - pip install .

script:
 - echo "can't test on Travis CI"
